from __future__ import annotations
from collections import defaultdict
RULE_FAMILIES={"CBAM":(True,"CBAM"),"ESPR":(False,"ESPR"),"DPP":(False,"DPP"),"REACH":(True,"REACH"),"ORIGIN":(True,"Origin"),"CUSTOMS":(True,"Customs"),"FTA":(False,"FTA preference"),"CUSTOMER":(True,"Buyer requirements"),"GPP":(False,"Green public procurement"),"EPD":(False,"EPD / environmental declaration"),"CERTIFICATION":(True,"Certification"),"SANCTIONS":(True,"Sanctions / restricted party"),"CARBON":(False,"Product carbon footprint"),"PACKAGING":(True,"Packaging"),"DOCUMENTATION":(True,"Documentation")}
RULE_META={k:{"blocking":v[0],"label":v[1]} for k,v in RULE_FAMILIES.items()}; BASE_PASS={k:"PASS" for k in RULE_FAMILIES}
def states(**changes):return {**BASE_PASS,**changes}
DEMO_ORDERS=[
{"order_id":"DEMO-EU-001","destination":"Germany","product":"HRC","cn_code":"7208","value_eur":2810000,"tonnes":4100,"customer":"Demo automotive buyer","supplier":"ABC Ferroalloys Ltd","owner":"Sustainability, Vijayanagar","expected_date":"2026-09-02","gross_margin_pct":.158,"cbam_exposure_eur":74000,"fta_tariff_saving_eur":0,"potential_fta_tariff_saving_eur":63000,"compliance_cost_eur":4800,"states":states(ESPR="PARTIAL",GPP="PARTIAL")},
{"order_id":"DEMO-EU-002","destination":"Netherlands","product":"HRC","cn_code":"7208","value_eur":1940000,"tonnes":2850,"customer":"Demo service centre","supplier":"ABC Ferroalloys Ltd","owner":"Export documentation","expected_date":"2026-08-31","gross_margin_pct":.145,"cbam_exposure_eur":51000,"fta_tariff_saving_eur":0,"potential_fta_tariff_saving_eur":41000,"compliance_cost_eur":6200,"states":states(ORIGIN="MISSING",FTA="MISSING")},
{"order_id":"DEMO-EU-003","destination":"Italy","product":"HRC","cn_code":"7208","value_eur":1360000,"tonnes":2000,"customer":"Demo industrial buyer","supplier":"XYZ Coke & Minerals","owner":"Procurement, Vijayanagar","expected_date":"2026-08-30","gross_margin_pct":.151,"cbam_exposure_eur":39000,"fta_tariff_saving_eur":0,"potential_fta_tariff_saving_eur":27000,"compliance_cost_eur":8900,"states":states(CBAM="MISSING",CARBON="PARTIAL",DOCUMENTATION="PARTIAL")},
{"order_id":"DEMO-EU-004","destination":"France","product":"HRC","cn_code":"7208","value_eur":980000,"tonnes":1420,"customer":"Demo processor","supplier":"Demo packaging vendor","owner":"International Trade","expected_date":"2026-09-01","gross_margin_pct":.139,"cbam_exposure_eur":26000,"fta_tariff_saving_eur":0,"potential_fta_tariff_saving_eur":19000,"compliance_cost_eur":5100,"states":states(CUSTOMS="MISSING",PACKAGING="MISSING")},
{"order_id":"DEMO-EU-005","destination":"Belgium","product":"HRC","cn_code":"7208","value_eur":720000,"tonnes":1050,"customer":"Demo distributor","supplier":"ABC Ferroalloys Ltd","owner":"International Trade","expected_date":None,"gross_margin_pct":.162,"cbam_exposure_eur":18000,"fta_tariff_saving_eur":0,"potential_fta_tariff_saving_eur":14000,"compliance_cost_eur":3600,"states":states()}]
OUTPUT_DEPENDENCIES={"cbam":["CBAM","CARBON","DOCUMENTATION"],"dpp":["DPP","ESPR","EPD","CARBON"],"export_package":["CBAM","ORIGIN","CUSTOMS","CERTIFICATION","SANCTIONS","PACKAGING","DOCUMENTATION"],"certificate_of_origin":["ORIGIN"],"customs_dossier":["CUSTOMS","SANCTIONS","DOCUMENTATION"]}
def compile_order(order):
 blockers=[]; warnings=[]; evaluations=[]
 for code,meta in RULE_META.items():
  status=order["states"].get(code,"MISSING"); item={"code":code,"label":meta["label"],"status":status,"blocking":meta["blocking"]}; evaluations.append(item)
  if meta["blocking"] and status!="PASS":blockers.append(item)
  elif status!="PASS":warnings.append(item)
 ready=not blockers; gross=order["value_eur"]*order["gross_margin_pct"]; expected=gross-order["cbam_exposure_eur"]+order["fta_tariff_saving_eur"]-order["compliance_cost_eur"]
 outputs={name:("GENERATABLE" if all(order["states"].get(x)=="PASS" for x in deps) else "NEEDS_DATA") for name,deps in OUTPUT_DEPENDENCIES.items()}
 return {**order,"market_ready":ready,"blockers":blockers,"warnings":warnings,"evaluations":evaluations,"economics":{"gross_margin_eur":round(gross,2),"cbam_exposure_eur":order["cbam_exposure_eur"],"fta_tariff_saving_eur":order["fta_tariff_saving_eur"],"potential_fta_tariff_saving_eur":order.get("potential_fta_tariff_saving_eur",0),"fta_legal_status":"NEGOTIATED_NOT_IN_FORCE","compliance_cost_eur":order["compliance_cost_eur"],"expected_landed_margin_eur":round(expected,2)},"outputs":outputs}
def order_book():
 compiled=[compile_order(x) for x in DEMO_ORDERS]; total=sum(x["value_eur"] for x in compiled); ready=sum(x["value_eur"] for x in compiled if x["market_ready"]); risk=defaultdict(float); countries=defaultdict(lambda:{"total":0,"at_risk":0})
 for x in compiled:
  countries[x["destination"]]["total"]+=x["value_eur"]; countries[x["destination"]]["at_risk"]+=0 if x["market_ready"] else x["value_eur"]
  for b in x["blockers"]:risk[b["code"]]+=x["value_eur"]
 fta_eligible=sum(x["value_eur"] for x in compiled if x["states"]["ORIGIN"]=="PASS"); fta_used=sum(x["value_eur"] for x in compiled if x["states"]["FTA"]=="PASS" and x["states"]["ORIGIN"]=="PASS"); current=sum(x["economics"]["expected_landed_margin_eur"] for x in compiled if x["market_ready"]); remediated=sum(x["economics"]["expected_landed_margin_eur"] for x in compiled)
 return {"data_status":"SYNTHETIC_OPERATIONAL_DEMO","warning":"Commercial orders, counterparties, values, margins and readiness states are synthetic. EU-India FTA savings are potential only while the negotiated FTA is not in force.","metrics":{"eu_order_book_eur":total,"market_ready_value_eur":ready,"revenue_at_risk_eur":total-ready,"market_ready_value_pct":round(100*ready/total,1),"cbam_exposure_eur":sum(x["cbam_exposure_eur"] for x in compiled),"fta_tariff_saving_eur":sum(x["fta_tariff_saving_eur"] for x in compiled),"potential_fta_tariff_saving_eur":sum(x.get("potential_fta_tariff_saving_eur",0) for x in compiled),"fta_legal_status":"NEGOTIATED_NOT_IN_FORCE","fta_utilisation_pct":round(100*fta_used/fta_eligible,1) if fta_eligible else 0,"compliance_cost_eur":sum(x["compliance_cost_eur"] for x in compiled),"value_unlocked_by_remediation_eur":round(remediated-current,2)},"risk_by_rule_family":[{"code":k,"label":RULE_META[k]["label"],"value_eur":v} for k,v in sorted(risk.items(),key=lambda z:z[1],reverse=True)],"risk_by_country":[{"country":k,**v} for k,v in countries.items()],"orders":compiled,"rule_families":RULE_META}
