from __future__ import annotations
from collections import defaultdict
from .db import connect,rows
REMEDIATION_PLAYBOOKS={
 "IDENTITY":{"title":"Confirm product identity and CN classification","owner":"Export documentation","timeline":"1–2 working days","cost":"Internal documentation effort; no external spend in the normal case.","story":["{no} ({product} to {country}, {value}) is blocked because product identity and CN classification are not evidenced. Every downstream check — duty rate, quota category, CBAM goods category — keys off this classification.","The fix is to confirm the product specification against the declared CN code, attach the mill test certificate, and lock the classification against the current TARIC snapshot so the treatment is date-specific and reproducible.","{unlock}"],"steps":[{"action":"Confirm product specification (grade, dimensions, processing) against the declared CN code","owner":"Export documentation","artifact":"Product spec sheet"},{"action":"Attach the mill test certificate for the shipped heats","owner":"Quality / plant","artifact":"Mill test certificate (PDF)"},{"action":"Lock the CN treatment against the current TARIC snapshot for the shipment date","owner":"Customs / export operations","artifact":"TARIC snapshot reference"}],"evidence":["Product specification","Mill test certificate","TARIC snapshot reference for the shipment date"]},
 "GENEALOGY":{"title":"Rebuild the heat → slab → coil genealogy for this shipment","owner":"Plant / MES","timeline":"3–5 working days once MES access is granted","cost":"Mostly internal plant-data effort; external cost only if MES extraction needs vendor help.","story":["{no} ({product} to {country}, {value}) is blocked because EuroSetu cannot trace the shipped coils back through slab and heat records. Without that chain, origin analysis, CBAM installation allocation and verifier sampling all stall.","The fix is a data-join exercise, not a metallurgy exercise: pull the heat numbers cast during the production window, follow them through slab IDs to coil IDs, and attach the MES genealogy extract to the shipment.","{unlock}"],"steps":[{"action":"Pull heat, slab and coil IDs for the shipment production window from MES","owner":"Plant / MES","artifact":"MES genealogy extract (CSV/API)"},{"action":"Join heat → slab → coil → shipment and flag untraced tonnage","owner":"Plant / MES","artifact":"Genealogy coverage sheet with % traced"},{"action":"Attach the extract as shipment evidence and re-run readiness","owner":"Export operations","artifact":"Evidence record linked to GENEALOGY"}],"evidence":["MES heat/slab/coil extract","Coverage sheet showing traced tonnage vs shipped tonnage"]},
 "CBAM_ACTIVITY":{"title":"Map metered installation and activity data to the goods","owner":"Plant energy / EMS","timeline":"1–2 weeks depending on meter coverage","cost":"Internal EMS/SCADA effort plus methodology review; verifier time if sampling is required.","story":["{no} ({product} to {country}, {value}) is blocked because CBAM installation and activity data are missing. The CBAM calculation cannot use actual emissions without knowing which production processes, fuels and meters belong to these goods.","The fix is to map the production route to metered observations — fuels consumed, electricity, process inputs — from EMS/SCADA and the laboratory, then allocate those quantities to the shipped tonnage using the documented methodology.","{unlock}"],"steps":[{"action":"Map the production route (sinter, blast furnace, BOF/EAF, rolling) to meters and cost centres","owner":"Plant energy / EMS","artifact":"Process-to-meter map"},{"action":"Pull metered fuel, electricity and activity observations for the production window","owner":"Plant energy / EMS","artifact":"Activity records (metered observations)"},{"action":"Allocate activity quantities to the shipped tonnage per the CBAM methodology","owner":"Sustainability","artifact":"Allocation sheet with methodology reference"}],"evidence":["Process-to-meter map","Metered activity records","Allocation sheet with methodology reference"]},
 "CBAM_EMISSIONS":{"title":"Compute embedded emissions with actual data instead of defaults","owner":"Sustainability","timeline":"About 1 week once activity data is mapped","cost":"Internal calculation effort; defaults remain the fallback and usually cost more at the border.","story":["{no} ({product} to {country}, {value}) is blocked because no embedded-emissions calculation exists. Without actuals the shipment falls back to default values, which overstate exposure and cannot be verified.","The fix is to run the versioned CBAM engine over the mapped activity data and precursor inputs, persist the calculation with its methodology version, and compare against defaults so the commercial benefit is visible.","{unlock}"],"steps":[{"action":"Confirm activity data and precursor inputs are mapped for the shipment window","owner":"Sustainability","artifact":"Activity + precursor input sheet"},{"action":"Run the versioned CBAM calculation engine and persist the result","owner":"Sustainability","artifact":"Versioned CBAM calculation record"},{"action":"Compare actuals vs defaults and record the exposure delta","owner":"Sustainability / finance","artifact":"Actuals-vs-defaults comparison"}],"evidence":["Versioned CBAM calculation record","Methodology reference","Actuals-vs-defaults comparison"]},
 "CBAM_VERIFICATION":{"title":"Secure the accredited verifier statement for actual emissions","owner":"Compliance / verifier","timeline":"2–4 weeks including findings closure","cost":"Verifier engagement fee; the largest external cost in the CBAM chain, scoped per installation.","story":["{no} ({product} to {country}, {value}) is blocked because actual-emissions figures require an accredited verifier statement before they can be used in the definitive CBAM period.","The fix is to engage the verifier early, give them the calculation pack plus underlying activity evidence, close any findings they raise, and file the statement against the shipment.","{unlock}"],"steps":[{"action":"Engage an accredited verifier and share the CBAM calculation pack","owner":"Compliance","artifact":"Verifier engagement + calculation pack"},{"action":"Close verifier findings with additional evidence where requested","owner":"Compliance / plant","artifact":"Findings closure log"},{"action":"File the verification statement against the shipment","owner":"Compliance","artifact":"Verification statement"}],"evidence":["Verifier engagement","Findings closure log","Verification statement"]},
 "SUPPLIER_DATA":{"title":"Close the precursor supplier evidence gap","owner":"Procurement","timeline":"1–3 weeks depending on supplier responsiveness","cost":"Supplier effort plus verifier review; far cheaper than default precursor values at the border.","story":["{no} ({product} to {country}, {value}) is blocked because required precursor supplier data is missing. CBAM precursor emissions (for example ferroalloys) cannot use actuals until the supplier's evidence is on file and verified.","The fix runs through the evidence cycle on this dashboard: raise the request from the drilldown with an owner and due date, the supplier submits the precursor file (PENDING), the verifier marks it VERIFIED, and the request resolves — flipping this requirement to PASS.","{unlock}"],"steps":[{"action":"Raise the evidence request to the precursor supplier with owner and due date","owner":"Procurement","artifact":"OPEN evidence request"},{"action":"Supplier submits the precursor emissions file or certificate","owner":"Supplier","artifact":"Supplier evidence (PENDING)"},{"action":"Verifier reviews and marks the evidence VERIFIED, then resolve the request","owner":"Verifier / procurement","artifact":"VERIFIED evidence + RESOLVED request"}],"evidence":["Precursor emissions file or certificate","Verifier approval","Resolved evidence request"]},
 "_DEFAULT":{"title":"Clear the blocking requirement with documented evidence","owner":"Shipment owner","timeline":"Varies by requirement — see the requirement notes","cost":"Estimate case by case in the simulator before committing spend.","story":["{no} ({product} to {country}, {value}) is blocked on a requirement that needs documented evidence before the shipment can be treated as market-ready.","The fix is to identify the exact artifact the requirement demands, assign a single owner, collect the evidence, and re-run readiness so the flip to PASS is recorded and auditable.","{unlock}"],"steps":[{"action":"Identify the exact artifact the blocking requirement demands","owner":"Shipment owner","artifact":"Requirement evidence checklist"},{"action":"Assign a single owner and due date, then collect the evidence","owner":"Shipment owner","artifact":"Evidence record"},{"action":"Re-run readiness and confirm the requirement flips to PASS","owner":"Export operations","artifact":"Updated readiness signal"}],"evidence":["Requirement evidence checklist","Evidence record"]}}
def _proposed_solution(target,shipment,becomes_ready,unlocked,estimated_cost,remaining):
 code=target["code"]; pb=REMEDIATION_PLAYBOOKS.get(code,REMEDIATION_PLAYBOOKS["_DEFAULT"])
 value=shipment["value_eur"]; v=f"€{value:,.0f}"
 if becomes_ready:unlock=f"Clearing this last blocker moves the full {v} from revenue-at-risk to market-ready."
 elif remaining:unlock=f"Clearing it does not unlock revenue yet — {remaining[0]['code']} ({remaining[0]['label']}) becomes the next blocker, with {len(remaining)} blocking requirement(s) left."
 else:unlock="No blocking requirements remain."
 ctx={"no":shipment["shipment_no"],"product":shipment.get("product") or "steel goods","country":shipment["destination_country"],"value":v,"n":len(remaining)+1,"unlock":unlock}
 net=max(0.0,unlocked-estimated_cost)
 return {"requirement_code":code,"title":pb["title"],"headline":f"{shipment['shipment_no']}: {pb['title']} — {unlock}","story":[p.format(**ctx) for p in pb["story"]],"steps":pb["steps"],"evidence_checklist":pb["evidence"],"owner_suggestion":pb["owner"],"typical_timeline":pb["timeline"],"cost_guidance":pb["cost"],"economics":{"revenue_unlocked_eur":unlocked,"estimated_remediation_cost_eur":estimated_cost,"net_value_unlocked_eur":net},"honesty_note":"What-if simulation only. No compliance state or evidence record was changed."}
def _risk_row(shipment,req,links,requests):
 supplier_rows=[]
 for link in links:
  if link["shipment_id"]!=shipment["id"]:continue
  supplier_rows.append({"supplier_id":link["supplier_id"],"supplier_name":link["supplier_name"],"material":link["material"],"required_evidence_type":link["required_evidence_type"],"request_id":link.get("request_id"),"request_status":link.get("request_status"),"owner":link.get("owner"),"due_date":link.get("due_date")})
 return {"shipment_id":shipment["id"],"shipment_no":shipment["shipment_no"],"country":shipment["destination_country"],"product":shipment["product"],"value_eur":shipment["value_eur"],"blocker":{"code":req["code"],"label":req["label"],"status":req["status"],"notes":req["notes"]},"suppliers":supplier_rows}
def risk_drilldown():
 with connect() as conn:
  shipments=rows(conn,"SELECT * FROM shipments WHERE value_eur>0 ORDER BY value_eur DESC")
  reqs=rows(conn,"SELECT * FROM requirements WHERE blocking=1 AND status!='PASS'")
  links=rows(conn,"""SELECT l.*,s.name supplier_name,r.id request_id,r.status request_status,r.owner,r.due_date
   FROM supplier_shipment_links l JOIN suppliers s ON s.id=l.supplier_id
   LEFT JOIN evidence_requests r ON r.shipment_id=l.shipment_id AND r.supplier_id=l.supplier_id AND r.status='OPEN'""")
 by_shipment=defaultdict(list)
 for r in reqs:by_shipment[r["shipment_id"]].append(r)
 countries=defaultdict(lambda:{"total_value_eur":0.0,"at_risk_value_eur":0.0,"shipments":[]})
 rule_risk=defaultdict(float); at_risk_shipments=set(); drill=[]
 for s in shipments:
  countries[s["destination_country"]]["total_value_eur"]+=s["value_eur"]
  blockers=by_shipment.get(s["id"],[])
  if blockers:
   at_risk_shipments.add(s["id"]); countries[s["destination_country"]]["at_risk_value_eur"]+=s["value_eur"]
   for r in blockers:
    rule_risk[r["code"]]+=s["value_eur"]; drill.append(_risk_row(s,r,links,[]))
   countries[s["destination_country"]]["shipments"].append({"shipment_id":s["id"],"shipment_no":s["shipment_no"],"value_eur":s["value_eur"],"blocker_count":len(blockers)})
 total=sum(s["value_eur"] for s in shipments); risk=sum(s["value_eur"] for s in shipments if s["id"] in at_risk_shipments)
 return {"data_status":"CONNECTED_SHIPMENT_DATA","metrics":{"eu_order_book_eur":total,"market_ready_value_eur":total-risk,"revenue_at_risk_eur":risk,"market_ready_value_pct":round(100*(total-risk)/total,1) if total else 0},"countries":[{"country":k,**v} for k,v in sorted(countries.items(),key=lambda x:x[1]["at_risk_value_eur"],reverse=True)],"rule_risk":[{"code":k,"value_eur":v} for k,v in sorted(rule_risk.items(),key=lambda x:x[1],reverse=True)],"drilldown":drill}

def simulate_remediation(shipment_id,requirement_code,estimated_cost_eur=0.0):
 with connect() as conn:
  shipment=rows(conn,"SELECT * FROM shipments WHERE id=? OR shipment_no=?",(shipment_id,shipment_id))
  if not shipment:raise ValueError("shipment not found")
  s=shipment[0]
  requirements=rows(conn,"SELECT * FROM requirements WHERE shipment_id=? AND blocking=1 ORDER BY code",(s["id"],))
 target=next((r for r in requirements if r["code"]==requirement_code),None)
 if not target:raise ValueError("blocking requirement not found")
 before=[r for r in requirements if r["status"]!="PASS"]
 after=[r for r in before if r["code"]!=requirement_code]
 was_ready=not before; becomes_ready=not after
 unlocked=s["value_eur"] if (not was_ready and becomes_ready) else 0.0
 remaining=[{"code":r["code"],"label":r["label"],"status":r["status"]} for r in after]
 return {"simulation":True,"mutated":False,"shipment_id":s["id"],"shipment_no":s["shipment_no"],"requirement":{"code":target["code"],"label":target["label"],"from_status":target["status"],"simulated_status":"PASS"},"before":{"market_ready":was_ready,"blocking_requirements":len(before),"revenue_at_risk_eur":0.0 if was_ready else s["value_eur"]},"after":{"market_ready":becomes_ready,"blocking_requirements":len(after),"revenue_at_risk_eur":0.0 if becomes_ready else s["value_eur"],"revenue_unlocked_eur":unlocked,"estimated_remediation_cost_eur":estimated_cost_eur,"net_value_unlocked_eur":max(0.0,unlocked-estimated_cost_eur),"next_blocker":remaining[0] if remaining else None,"remaining_blockers":remaining},"proposed_solution":_proposed_solution(target,s,becomes_ready,unlocked,estimated_cost_eur,remaining),"notice":"What-if simulation only. No compliance state or evidence record was changed."}
