from __future__ import annotations
from datetime import datetime,timezone
from uuid import uuid5,NAMESPACE_URL
from .db import connect
from .rules import STEEL_EU_RULES
CASE_ID=str(uuid5(NAMESPACE_URL,"setu-jsw-vijayanagar-public-case-2026"))
PUBLIC_CASE=dict(shipment_no="PUBLIC-JSW-VJ-HRC-EU-2026",exporter="JSW Steel Limited",facility="Vijayanagar Works, Karnataka, India",importer="EU importer (not publicly identified)",destination_country="EU",product="Hot Rolled Coils",cn_code="7208 family (representative; shipment-level CN not public)",tonnes=1.0,value_eur=0.0,emissions_method="public EPD / CBAM plant-wise accounting",embedded_emissions_tco2e_per_t=None,supplier_required=4,supplier_complete=3,manual_hours=0.0)
SOURCES=[("JSW FY2025-26 Integrated Annual Report — export performance","https://www.jswsteel.in/jsw-steel-annual-report-2025-26/mda.html","2026","Company reports ~2.80 MnT exports; Europe was 66.8%; JSW Steel HRC exports were 1.13 MnT."),("JSW FY2025-26 Integrated Annual Report — risk management","https://www.jswsteel.in/jsw-steel-annual-report-2025-26/risk-management.html","2026","Company says it performed plant-wise emissions accounting aligned with EU methodologies and engaged EU-ETS-accredited third-party verifiers."),("International EPD System — JSW Vijayanagar Hot Rolled Coils","https://www.environdec.com/library/epd5172","2026-03-13","Third-party verified EPD EPD-IES-0005172:001 for JSW Steel hot rolled coils from Vijayanagar."),("JSW Vijayanagar Works — certifications","https://www.jswsteel.in/facility/vijayanagar-works","2026","Public plant page lists HSM certifications and product declarations."),("European Commission — CBAM communication template","https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-communication-and-news_en","2026","Commission provides installation communication templates and steel examples; actual values require verified producer emissions data.")]
REQ={"IDENTITY":("PASS",1,"Public product/site evidence; exact shipment CN is private."),"GENEALOGY":("PARTIAL",1,"Public process route exists; heat/slab/coil IDs are private."),"CBAM_ACTIVITY":("PARTIAL",2,"Public route/system-boundary evidence exists; installation dataset is private."),"CBAM_EMISSIONS":("PARTIAL",2,"EPD is environmental evidence, not asserted as CBAM embedded emissions."),"CBAM_VERIFICATION":("PASS",1,"Company reports accredited third-party CBAM verification engagement."),"SUPPLIER_DATA":("PARTIAL",0,"Shipment supplier declarations are private."),"DPP_ID":("MISSING",0,"No public shipment/coil DPP identifier."),"DPP_MATERIAL":("PARTIAL",1,"Public material evidence is not shipment-specific."),"DPP_TECH":("PASS",1,"Public EPD provides technical properties.")}
def seed_if_empty():
 now=datetime.now(timezone.utc).isoformat()
 with connect() as conn:
  marker=conn.execute("SELECT value FROM app_meta WHERE key='seed_version'").fetchone()
  if marker and marker[0]=="public-jsw-v2":return
  for t in ("evidence","verifications","requirements","shipments","public_sources"):conn.execute(f"DELETE FROM {t}")
  s=PUBLIC_CASE; conn.execute("INSERT INTO shipments(id,shipment_no,exporter,facility,importer,destination_country,product,cn_code,tonnes,value_eur,emissions_method,embedded_emissions_tco2e_per_t,supplier_required,supplier_complete,manual_hours,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",(CASE_ID,s["shipment_no"],s["exporter"],s["facility"],s["importer"],s["destination_country"],s["product"],s["cn_code"],s["tonnes"],s["value_eur"],s["emissions_method"],s["embedded_emissions_tco2e_per_t"],s["supplier_required"],s["supplier_complete"],s["manual_hours"],now,now))
  for r in STEEL_EU_RULES:
   status,ec,notes=REQ[r.code]; conn.execute("INSERT INTO requirements(shipment_id,code,label,category,blocking,status,required_evidence,evidence_count,notes) VALUES(?,?,?,?,?,?,?,?,?)",(CASE_ID,r.code,r.label,r.category,int(r.blocking),status,r.required_evidence,ec,notes))
  for title,url,pub,claim in SOURCES:conn.execute("INSERT INTO public_sources(shipment_id,title,url,published,claim) VALUES(?,?,?,?,?)",(CASE_ID,title,url,pub,claim))
  conn.execute("INSERT OR REPLACE INTO app_meta(key,value) VALUES('seed_version','public-jsw-v2')")
